# Generated by Django 5.2.9 on 2025-12-29 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subtipo',
            fields=[
                ('id_subtipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_subtipo', models.CharField(max_length=100)),
                ('esp_vidamin', models.IntegerField()),
                ('esp_vidamax', models.IntegerField()),
                ('desc_subtipo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subtipo_exotico',
            fields=[
                ('id_subtipo', models.OneToOneField(db_column='id_subtipo', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.subtipo')),
                ('min_size', models.IntegerField()),
                ('max_size', models.IntegerField()),
                ('nivel_interaccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subtipo_Mamifero',
            fields=[
                ('id_subtipo', models.OneToOneField(db_column='id_subtipo', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.subtipo')),
                ('peso_min', models.FloatField()),
                ('peso_max', models.FloatField()),
                ('size_subtipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='subtipo',
            name='id_tipo',
            field=models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='api.tipo'),
        ),
    ]
