# Generated by Django 5.2.9 on 2025-12-30 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto_emergencia',
            fields=[
                ('id_contacto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_p', models.CharField(max_length=100)),
                ('apellido_m', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('no_habit', models.BigAutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=50)),
                ('costo', models.FloatField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.BigAutoField(primary_key=True, serialize=False)),
                ('puesto', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=20)),
                ('costo', models.FloatField()),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoCP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigoP', models.CharField(max_length=5)),
                ('id_asenta', models.IntegerField()),
                ('d_asenta', models.CharField(max_length=200)),
                ('d_tipo_asenta', models.CharField(max_length=50)),
                ('d_mnpio', models.CharField(max_length=100)),
                ('d_estado', models.CharField(max_length=100)),
                ('id_estado', models.CharField(max_length=5)),
                ('id_tipo_asenta', models.CharField(max_length=5)),
                ('id_mnpio', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['codigoP'], name='codigoP_idx'), models.Index(fields=['codigoP', 'id_asenta'], name='cp_asenta_idx')],
                'constraints': [models.UniqueConstraint(fields=('codigoP', 'id_asenta'), name='unique_cp_asenta')],
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_calle', models.CharField(max_length=150)),
                ('num_ext', models.CharField(max_length=10)),
                ('num_int', models.CharField(blank=True, max_length=10, null=True)),
                ('catalogo', models.ForeignKey(db_column='catalogo_id', on_delete=django.db.models.deletion.PROTECT, to='api.catalogocp')),
            ],
        ),
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('id_dueño', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_p', models.CharField(max_length=100)),
                ('apellido_m', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('id_contacto', models.ForeignKey(db_column='id_contacto', on_delete=django.db.models.deletion.PROTECT, to='api.contacto_emergencia')),
                ('id_domicilio', models.ForeignKey(db_column='id_domicilio', on_delete=django.db.models.deletion.PROTECT, to='api.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('esterilizado', models.BooleanField()),
                ('chip', models.CharField(max_length=50, unique=True)),
                ('ruac', models.CharField(max_length=50, null=True, unique=True)),
                ('sexo', models.CharField(max_length=1)),
                ('color_prim', models.CharField(max_length=50)),
                ('color_sec', models.CharField(blank=True, max_length=50, null=True)),
                ('comportamiento', models.CharField(blank=True, max_length=200, null=True)),
                ('cartilla_vac', models.BooleanField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('id_dueño', models.ForeignKey(db_column='id_dueño', on_delete=django.db.models.deletion.PROTECT, to='api.dueño')),
                ('id_subtipo', models.ForeignKey(db_column='id_subtipo', on_delete=django.db.models.deletion.PROTECT, to='api.subtipo')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_p', models.CharField(max_length=100)),
                ('apellido_m', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('id_puesto', models.ForeignKey(db_column='id_puesto', on_delete=django.db.models.deletion.PROTECT, to='api.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('checke_in', models.DateTimeField()),
                ('checke_out', models.DateTimeField()),
                ('estatus', models.CharField(max_length=50)),
                ('id_dueño', models.ForeignKey(db_column='id_dueño', on_delete=django.db.models.deletion.PROTECT, to='api.dueño')),
                ('id_mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.PROTECT, to='api.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion_Servicio',
            fields=[
                ('id_res_serv', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_total', models.FloatField()),
                ('estatus', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, to='api.empleado')),
                ('id_reservacion', models.ForeignKey(db_column='id_reservacion', on_delete=django.db.models.deletion.PROTECT, to='api.reservacion')),
                ('no_habit', models.ForeignKey(db_column='no_habit', on_delete=django.db.models.deletion.PROTECT, to='api.habitacion')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, to='api.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id_vacuna', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_vac', models.CharField(max_length=100)),
                ('via_admin', models.CharField(max_length=50)),
                ('importancia', models.CharField(max_length=100)),
                ('tiempo_min', models.IntegerField()),
                ('tiempo_max', models.IntegerField()),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='api.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota_Vacuna',
            fields=[
                ('id_aplicacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('id_mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.PROTECT, to='api.mascota')),
                ('id_vac', models.ForeignKey(db_column='id_vacuna', on_delete=django.db.models.deletion.PROTECT, to='api.vacuna')),
            ],
        ),
        migrations.AddIndex(
            model_name='domicilio',
            index=models.Index(fields=['catalogo'], name='domicilio_cp_asenta_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservacion',
            constraint=models.CheckConstraint(condition=models.Q(('checke_out__gt', models.F('checke_in'))), name='checke_out_gt_checke_in'),
        ),
    ]
