# Generated by Django 5.2.9 on 2025-12-31 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contacto_emergencia_habitacion_puesto_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueño',
            name='id_contacto',
            field=models.ForeignKey(db_column='id_contacto', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.contacto_emergencia'),
        ),
        migrations.AlterField(
            model_name='dueño',
            name='id_domicilio',
            field=models.ForeignKey(db_column='id_domicilio', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.domicilio'),
        ),
    ]
