# Generated by Django 5.2.9 on 2026-01-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dueño_id_contacto_alter_dueño_id_domicilio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='edad',
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
