# Generated by Django 5.2.9 on 2026-01-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_mascota_edad_mascota_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='chip',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
