# Generated by Django 5.2.9 on 2026-01-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_mascota_chip'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='cartilla_vac',
            field=models.BooleanField(default=False),
        ),
    ]
