# Generated by Django 5.2.9 on 2026-01-04 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mascota_foto_alter_mascota_cartilla_vac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='id_dueño',
            field=models.ForeignKey(db_column='id_dueño', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.dueño'),
        ),
    ]
