# Generated by Django 5.2.9 on 2026-01-07 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoEdadPredispuesta',
            fields=[
                ('id_edad_predispuesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('rango_edad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoPatron',
            fields=[
                ('id_patron', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_patron', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoSeveridad',
            fields=[
                ('id_severidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel_severidad', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoSexo',
            fields=[
                ('id_sexo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre_sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoTipoVacuna',
            fields=[
                ('id_tipo_vacuna', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('codigoP', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id_color', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_pat', models.CharField(max_length=100)),
                ('apellido_mat', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.BigAutoField(primary_key=True, serialize=False)),
                ('d_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusHabit',
            fields=[
                ('id_status', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusReservacion',
            fields=[
                ('id_status', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MascotaBase',
            fields=[
                ('id_mascota', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('f_nac', models.DateField(blank=True, null=True)),
                ('esterilizado', models.BooleanField()),
                ('foto_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelGravedad',
            fields=[
                ('id_gravedad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_gravedad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NivelImportancia',
            fields=[
                ('id_importancia', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_importancia', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_servicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtipo',
            fields=[
                ('id_subtipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_subtipo', models.CharField(max_length=100)),
                ('esp_vidamin', models.IntegerField()),
                ('esp_vidamax', models.IntegerField()),
                ('desc_subtipo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_Tipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlergias',
            fields=[
                ('id_tipo_alergia', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAsentamiento',
            fields=[
                ('id_tipo_asenta', models.BigAutoField(primary_key=True, serialize=False)),
                ('d_tipo_asenta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoColor',
            fields=[
                ('id_tipo_color', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEnfermedad',
            fields=[
                ('id_tipo_enfermedad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_habitacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id_tipo_servicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
                ('requiere_habitacion', models.BooleanField(default=False)),
                ('requiere_duracion', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id_alergia', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_alergia', models.CharField(max_length=255)),
                ('agente_causal', models.TextField(blank=True, null=True)),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_edad_predispuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.catalogoedadpredispuesta')),
                ('id_gravedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.nivelgravedad')),
                ('id_subtipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.subtipo')),
                ('id_tipo_alergia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.tipoalergias')),
            ],
        ),
        migrations.CreateModel(
            name='Asentamiento',
            fields=[
                ('id_asenta', models.BigAutoField(primary_key=True, serialize=False)),
                ('d_asenta', models.CharField(max_length=200)),
                ('codigoP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.codigopostal')),
                ('id_tipo_asenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.tipoasentamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_calle', models.CharField(max_length=100)),
                ('num_calleext', models.CharField(max_length=10)),
                ('num_calleint', models.CharField(blank=True, max_length=10, null=True)),
                ('id_asenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.asentamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id_dueno', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_Mat', models.CharField(max_length=100)),
                ('apellido_Pat', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=255)),
                ('id_domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id_contacto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_pat', models.CharField(max_length=100)),
                ('apellido_mat', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=255)),
                ('id_dueno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_v2.dueno')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id_enfermedad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_enfermedad', models.CharField(max_length=255)),
                ('agente_causal', models.TextField(blank=True, null=True)),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('forma_transmision', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('prevencion', models.TextField(blank=True, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_edad_predispuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.catalogoedadpredispuesta')),
                ('id_gravedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.nivelgravedad')),
                ('id_subtipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.subtipo')),
                ('id_tipo_enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.tipoenfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('no_habit', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.estatushabit')),
                ('id_tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_v2.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='LimpiezaHabitacion',
            fields=[
                ('id_limpieza', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.empleado')),
                ('no_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='MascotaIdentificacion',
            fields=[
                ('id_mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_v2.mascotabase')),
                ('chip', models.CharField(blank=True, max_length=20, null=True)),
                ('ruac', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MascotaSalud',
            fields=[
                ('id_mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_v2.mascotabase')),
                ('cartilla_vac', models.BooleanField()),
                ('enfermedades', models.BooleanField()),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mascotabase',
            name='id_Duno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.dueno'),
        ),
        migrations.AddField(
            model_name='mascotabase',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.catalogosexo'),
        ),
        migrations.CreateModel(
            name='MascotaFisica',
            fields=[
                ('id_registro', models.BigAutoField(primary_key=True, serialize=False)),
                ('tamano', models.IntegerField(blank=True, null=True)),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.mascotabase')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_mnpio', models.BigAutoField(primary_key=True, serialize=False)),
                ('d_mnpio', models.CharField(max_length=50)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.estado')),
            ],
        ),
        migrations.AddField(
            model_name='codigopostal',
            name='id_mnpio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.municipio'),
        ),
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id_reservacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_reservacion', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('costo_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.dueno')),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.empleado')),
                ('id_mascota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.mascotabase')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.estatusreservacion')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraPaseo',
            fields=[
                ('id_paseo', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('ruta', models.TextField()),
                ('distancia', models.IntegerField(blank=True, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('kilometros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('id_reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.reservaciones')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.rol'),
        ),
        migrations.CreateModel(
            name='SubtipoExotico',
            fields=[
                ('id_subtipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_v2.subtipo')),
                ('min_size', models.IntegerField()),
                ('max_size', models.IntegerField()),
                ('nivel_interaccion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubtipoMamifero',
            fields=[
                ('id_subtipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_v2.subtipo')),
                ('peso_Min', models.IntegerField()),
                ('peso_Max', models.IntegerField()),
                ('size_subtipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mascotabase',
            name='id_subtipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.subtipo'),
        ),
        migrations.AddField(
            model_name='subtipo',
            name='id_Tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.tipo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.tiposervicio'),
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id_vacuna', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_vacuna', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('vigencia_dias', models.IntegerField()),
                ('id_importancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.nivelimportancia')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.tipo')),
                ('id_tipo_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.catalogotipovacuna')),
            ],
        ),
        migrations.CreateModel(
            name='MascotaAlergias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diagnostico', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('id_alergia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.alergia')),
                ('id_severidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.catalogoseveridad')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.mascotabase')),
            ],
            options={
                'unique_together': {('id_mascota', 'id_alergia')},
            },
        ),
        migrations.CreateModel(
            name='MascotaEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diagnostico', models.DateField()),
                ('fecha_recuperacion', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('id_enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.enfermedad')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.mascotabase')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_recuperacion__isnull', True), ('fecha_recuperacion__gte', models.F('fecha_diagnostico')), _connector='OR'), name='recuperacion_check2')],
                'unique_together': {('id_mascota', 'id_enfermedad', 'fecha_diagnostico')},
            },
        ),
        migrations.CreateModel(
            name='ReservacionDuracion',
            fields=[
                ('id_reservacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_v2.reservaciones')),
                ('duracion_minutos', models.IntegerField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('duracion_minutos__gt', 0)), name='duracion_check2')],
            },
        ),
        migrations.CreateModel(
            name='MascotaColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.color')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.mascotabase')),
                ('id_patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.catalogopatron')),
                ('tipo_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.tipocolor')),
            ],
            options={
                'unique_together': {('id_mascota', 'id_color', 'tipo_color'), ('id_mascota', 'tipo_color')},
            },
        ),
        migrations.CreateModel(
            name='MascotaVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('fecha_refuerzo', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.mascotabase')),
                ('id_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.vacuna')),
            ],
            options={
                'unique_together': {('id_mascota', 'id_vacuna', 'fecha_aplicacion')},
            },
        ),
        migrations.CreateModel(
            name='VacunaPrevieneEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.enfermedad')),
                ('id_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.vacuna')),
            ],
            options={
                'unique_together': {('id_vacuna', 'id_enfermedad')},
            },
        ),
        migrations.CreateModel(
            name='ReservacionHotel',
            fields=[
                ('id_reservacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_v2.reservaciones')),
                ('fecha_checkin', models.DateTimeField(blank=True, null=True)),
                ('fecha_checkout', models.DateTimeField(blank=True, null=True)),
                ('fecha_checkin_prevista', models.DateField()),
                ('fecha_checkout_prevista', models.DateField()),
                ('noches_programadas', models.IntegerField(blank=True, null=True)),
                ('no_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.habitacion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_checkout__isnull', True), ('fecha_checkout__gte', models.F('fecha_checkin')), _connector='OR'), name='checkout_check2'), models.CheckConstraint(condition=models.Q(('fecha_checkout_prevista__gt', models.F('fecha_checkin_prevista'))), name='tiempo_check2')],
            },
        ),
    ]
