# Generated by Django 5.2.9 on 2026-01-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascotabase',
            old_name='id_Duno',
            new_name='id_dueno',
        ),
    ]
