# Generated by Django 5.2.9 on 2026-01-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0002_rename_id_duno_mascotabase_id_dueno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtipoexotico',
            name='nivel_interaccion',
            field=models.CharField(max_length=50),
        ),
    ]
