# Generated by Django 5.2.9 on 2026-01-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0003_alter_subtipoexotico_nivel_interaccion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dueno',
            table='api_v2_dueno',
        ),
    ]
