# Generated by Django 5.2.9 on 2026-01-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0004_alter_dueno_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='id_Tipo',
            new_name='id_tipo',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='Tipo',
            new_name='tipo',
        ),
    ]
