# Generated by Django 5.2.9 on 2026-01-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0005_rename_id_tipo_tipo_id_tipo_rename_tipo_tipo_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtipo',
            old_name='id_Tipo',
            new_name='id_tipo',
        ),
    ]
