# Generated by Django 5.2.9 on 2026-01-09 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0006_rename_id_tipo_subtipo_id_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dueno',
            old_name='apellido_Mat',
            new_name='apellido_mat',
        ),
        migrations.RenameField(
            model_name='dueno',
            old_name='apellido_Pat',
            new_name='apellido_pat',
        ),
    ]
