# Generated by Django 5.2.9 on 2026-01-10 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0007_rename_apellido_mat_dueno_apellido_mat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='id_asenta',
            field=models.ForeignKey(db_column='id_asenta', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.asentamiento'),
        ),
    ]
