# Generated by Django 5.2.9 on 2026-01-10 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0008_alter_domicilio_id_asenta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mascotacolor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vacunaprevieneenfermedad',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='alergia',
            name='id_edad_predispuesta',
            field=models.ForeignKey(db_column='id_edad_predispuesta', on_delete=django.db.models.deletion.CASCADE, to='api_v2.catalogoedadpredispuesta'),
        ),
        migrations.AlterField(
            model_name='alergia',
            name='id_gravedad',
            field=models.ForeignKey(db_column='id_gravedad', on_delete=django.db.models.deletion.CASCADE, to='api_v2.nivelgravedad'),
        ),
        migrations.AlterField(
            model_name='alergia',
            name='id_subtipo',
            field=models.ForeignKey(db_column='id_subtipo', on_delete=django.db.models.deletion.CASCADE, to='api_v2.subtipo'),
        ),
        migrations.AlterField(
            model_name='alergia',
            name='id_tipo_alergia',
            field=models.ForeignKey(db_column='id_tipo_alergia', on_delete=django.db.models.deletion.CASCADE, to='api_v2.tipoalergias'),
        ),
        migrations.AlterField(
            model_name='asentamiento',
            name='codigoP',
            field=models.ForeignKey(db_column='codigop', on_delete=django.db.models.deletion.CASCADE, to='api_v2.codigopostal'),
        ),
        migrations.AlterField(
            model_name='asentamiento',
            name='id_tipo_asenta',
            field=models.ForeignKey(db_column='id_tipo_asenta', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.tipoasentamiento'),
        ),
        migrations.AlterField(
            model_name='bitacorapaseo',
            name='id_reservacion',
            field=models.ForeignKey(db_column='id_reservacion', on_delete=django.db.models.deletion.CASCADE, to='api_v2.reservaciones'),
        ),
        migrations.AlterField(
            model_name='codigopostal',
            name='id_mnpio',
            field=models.ForeignKey(db_column='id_mnpio', on_delete=django.db.models.deletion.CASCADE, to='api_v2.municipio'),
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='id_dueno',
            field=models.OneToOneField(db_column='id_dueno', on_delete=django.db.models.deletion.CASCADE, to='api_v2.dueno'),
        ),
        migrations.AlterField(
            model_name='dueno',
            name='id_domicilio',
            field=models.ForeignKey(db_column='id_domicilio', on_delete=django.db.models.deletion.CASCADE, to='api_v2.domicilio'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='api_v2.rol'),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='id_edad_predispuesta',
            field=models.ForeignKey(db_column='id_edad_predispuesta', on_delete=django.db.models.deletion.CASCADE, to='api_v2.catalogoedadpredispuesta'),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='id_gravedad',
            field=models.ForeignKey(db_column='id_gravedad', on_delete=django.db.models.deletion.CASCADE, to='api_v2.nivelgravedad'),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='id_subtipo',
            field=models.ForeignKey(db_column='id_subtipo', on_delete=django.db.models.deletion.CASCADE, to='api_v2.subtipo'),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='id_tipo_enfermedad',
            field=models.ForeignKey(db_column='id_tipo_enfermedad', on_delete=django.db.models.deletion.CASCADE, to='api_v2.tipoenfermedad'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='id_status',
            field=models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.CASCADE, to='api_v2.estatushabit'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='id_tipo_habitacion',
            field=models.ForeignKey(db_column='id_tipo_habitacion', on_delete=django.db.models.deletion.PROTECT, to='api_v2.tipohabitacion'),
        ),
        migrations.AlterField(
            model_name='limpiezahabitacion',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='api_v2.empleado'),
        ),
        migrations.AlterField(
            model_name='limpiezahabitacion',
            name='no_habit',
            field=models.ForeignKey(db_column='no_habit', on_delete=django.db.models.deletion.CASCADE, to='api_v2.habitacion'),
        ),
        migrations.AlterField(
            model_name='mascotaalergias',
            name='id_alergia',
            field=models.ForeignKey(db_column='id_alergia', on_delete=django.db.models.deletion.CASCADE, to='api_v2.alergia'),
        ),
        migrations.AlterField(
            model_name='mascotaalergias',
            name='id_mascota',
            field=models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='api_v2.mascotabase'),
        ),
        migrations.AlterField(
            model_name='mascotaalergias',
            name='id_severidad',
            field=models.ForeignKey(db_column='id_severidad', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.catalogoseveridad'),
        ),
        migrations.AlterField(
            model_name='mascotabase',
            name='id_dueno',
            field=models.ForeignKey(db_column='id_dueno', on_delete=django.db.models.deletion.CASCADE, to='api_v2.dueno'),
        ),
        migrations.AlterField(
            model_name='mascotabase',
            name='id_subtipo',
            field=models.ForeignKey(db_column='id_subtipo', on_delete=django.db.models.deletion.CASCADE, to='api_v2.subtipo'),
        ),
        migrations.AlterField(
            model_name='mascotabase',
            name='sexo',
            field=models.ForeignKey(db_column='sexo', on_delete=django.db.models.deletion.CASCADE, to='api_v2.catalogosexo'),
        ),
        migrations.AlterField(
            model_name='mascotacolor',
            name='id_color',
            field=models.ForeignKey(db_column='id_color', on_delete=django.db.models.deletion.CASCADE, to='api_v2.color'),
        ),
        migrations.AlterField(
            model_name='mascotacolor',
            name='id_mascota',
            field=models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='api_v2.mascotabase'),
        ),
        migrations.AlterField(
            model_name='mascotacolor',
            name='id_patron',
            field=models.ForeignKey(db_column='id_patron', on_delete=django.db.models.deletion.CASCADE, to='api_v2.catalogopatron'),
        ),
        migrations.AlterField(
            model_name='mascotacolor',
            name='tipo_color',
            field=models.ForeignKey(db_column='tipo_color', on_delete=django.db.models.deletion.CASCADE, to='api_v2.tipocolor'),
        ),
        migrations.AlterField(
            model_name='mascotaenfermedad',
            name='id_mascota',
            field=models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='api_v2.mascotabase'),
        ),
        migrations.AlterField(
            model_name='mascotafisica',
            name='id_mascota',
            field=models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='api_v2.mascotabase'),
        ),
        migrations.AlterField(
            model_name='mascotavacuna',
            name='id_mascota',
            field=models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='api_v2.mascotabase'),
        ),
        migrations.AlterField(
            model_name='mascotavacuna',
            name='id_vacuna',
            field=models.ForeignKey(db_column='id_vacuna', on_delete=django.db.models.deletion.CASCADE, to='api_v2.vacuna'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='id_estado',
            field=models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='api_v2.estado'),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='id_dueno',
            field=models.ForeignKey(db_column='id_dueno', on_delete=django.db.models.deletion.CASCADE, to='api_v2.dueno'),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.empleado'),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='id_mascota',
            field=models.ForeignKey(db_column='id_mascota', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.mascotabase'),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='id_servicio',
            field=models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, to='api_v2.servicio'),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='id_status',
            field=models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.CASCADE, to='api_v2.estatusreservacion'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id_tipo_servicio',
            field=models.ForeignKey(db_column='id_tipo_servicio', on_delete=django.db.models.deletion.CASCADE, to='api_v2.tiposervicio'),
        ),
        migrations.AlterField(
            model_name='subtipo',
            name='id_tipo',
            field=models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='api_v2.tipo'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='id_importancia',
            field=models.ForeignKey(db_column='id_importancia', on_delete=django.db.models.deletion.CASCADE, to='api_v2.nivelimportancia'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='id_tipo',
            field=models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='api_v2.tipo'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='id_tipo_vacuna',
            field=models.ForeignKey(db_column='id_tipo_vacuna', on_delete=django.db.models.deletion.CASCADE, to='api_v2.catalogotipovacuna'),
        ),
        migrations.AlterField(
            model_name='vacunaprevieneenfermedad',
            name='id_enfermedad',
            field=models.ForeignKey(db_column='id_enfermedad', on_delete=django.db.models.deletion.CASCADE, to='api_v2.enfermedad'),
        ),
        migrations.AlterField(
            model_name='vacunaprevieneenfermedad',
            name='id_vacuna',
            field=models.ForeignKey(db_column='id_vacuna', on_delete=django.db.models.deletion.CASCADE, to='api_v2.vacuna'),
        ),
    ]
