# Generated by Django 5.2.9 on 2026-01-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0009_alter_mascotacolor_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigopostal',
            old_name='codigoP',
            new_name='codigop',
        ),
    ]
