# Generated by Django 5.2.9 on 2026-01-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0010_rename_codigop_codigopostal_codigop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asentamiento',
            old_name='codigoP',
            new_name='codigop',
        ),
    ]
