# Generated by Django 5.2.9 on 2026-01-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0011_rename_codigop_asentamiento_codigop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dueno',
            table=None,
        ),
    ]
